Results of doctest builder run on 2014-01-24 22:20:09
=====================================================

Document: api_documentation
---------------------------
**********************************************************************
File "api_documentation.rst", line 43, in default
Failed example:
    redis_client = redis.StrictClient(host='X.X.X.X', port=6379, db=1)
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[4]>", line 1, in <module>
        redis_client = redis.StrictClient(host='X.X.X.X', port=6379, db=1)
    AttributeError: 'module' object has no attribute 'StrictClient'
**********************************************************************
File "api_documentation.rst", line 44, in default
Failed example:
    sherlock.configure(client=redis_client)
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[5]>", line 1, in <module>
        sherlock.configure(client=redis_client)
    NameError: name 'redis_client' is not defined
**********************************************************************
File "api_documentation.rst", line 191, in default
Failed example:
    time.sleep(2)
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[4]>", line 1, in <module>
        time.sleep(2)
    NameError: name 'time' is not defined
**********************************************************************
File "api_documentation.rst", line 221, in default
Failed example:
    lock.acquire()
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[3]>", line 1, in <module>
        lock.acquire()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 179, in acquire
        'lock.' % self.timeout)
    LockTimeoutException: Timeout elapsed after 2 seconds while trying to acquiring lock.
**********************************************************************
File "api_documentation.rst", line 225, in default
Failed example:
    lock.acquire()
Expected:
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "sherlock/lock.py", line 170, in acquire
        'lock.' % self.timeout)
    sherlock.lock.LockTimeoutException: Timeout elapsed after 2 seconds while trying to acquiring lock.
Got:
    True
**********************************************************************
File "api_documentation.rst", line 51, in default
Failed example:
    sherlock.configure(sherlock.backends.REDIS)
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[2]>", line 1, in <module>
        sherlock.configure(sherlock.backends.REDIS)
    TypeError: configure() takes exactly 0 arguments (1 given)
**********************************************************************
File "api_documentation.rst", line 57, in default
Failed example:
    lock.acquire()
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[4]>", line 1, in <module>
        lock.acquire()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 179, in acquire
        'lock.' % self.timeout)
    LockTimeoutException: Timeout elapsed after 2 seconds while trying to acquiring lock.
**********************************************************************
File "api_documentation.rst", line 65, in default
Failed example:
    lock.release()
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[6]>", line 1, in <module>
        lock.release()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 196, in release
        return self._release()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 302, in _release
        return self._lock_proxy.release()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 196, in release
        return self._release()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 425, in _release
        raise LockException('Lock was not set by this process.')
    LockException: Lock was not set by this process.
**********************************************************************
File "api_documentation.rst", line 68, in default
Failed example:
    lock.locked()
Expected:
    False
Got:
    True
**********************************************************************
File "api_documentation.rst", line 76, in default
Failed example:
    lock.acquire()
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[11]>", line 1, in <module>
        lock.acquire()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 179, in acquire
        'lock.' % self.timeout)
    LockTimeoutException: Timeout elapsed after 2 seconds while trying to acquiring lock.
**********************************************************************
File "api_documentation.rst", line 82, in default
Failed example:
    with Lock('my_lock') as lock:
        # do some stuff with your acquired resource
        pass
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest default[13]>", line 1, in <module>
        with Lock('my_lock') as lock:
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 199, in __enter__
        self.acquire()
      File "/Users/vkapoor/Development/sherlock/sherlock/lock.py", line 179, in acquire
        'lock.' % self.timeout)
    LockTimeoutException: Timeout elapsed after 2 seconds while trying to acquiring lock.
**********************************************************************
1 items had failures:
  11 of  85 in default
85 tests in 1 items.
74 passed and 11 failed.
***Test Failed*** 11 failures.

Doctest summary
===============
   85 tests
   11 failures in tests
    0 failures in setup code
    0 failures in cleanup code
